# Generated by Django 3.2.5 on 2022-02-22 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageuploadingtest',
            name='application_round',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='application_management.applicationround'),
        ),
    ]
