# Generated by Django 3.2.5 on 2022-02-22 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_management', '0002_imageuploadingtest_application_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationround',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
