# Generated by Django 3.2.5 on 2022-03-08 13:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application_management', '0003_applicationround_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageUploadingTest',
            new_name='ApplicationFormModel',
        ),
    ]
