# Generated by Django 3.2.5 on 2022-03-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_management', '0005_auto_20220308_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationformmodel',
            name='middlename',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
