# Generated by Django 3.2.5 on 2022-03-08 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_management', '0006_alter_applicationformmodel_middlename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationformmodel',
            name='optional_work',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
